let supabaseClient=null,currentUser=null,currentActivity=null,currentReport=null,profile={name:'',school:'',logo:''};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showView(name){['login','register','forgot','reset'].forEach(v=>$(v+'Panel').classList.toggle('hidden',v!==name));$('authMessage').classList.add('hidden')}
function msg(text){$('authMessage').textContent=text;$('authMessage').classList.remove('hidden')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
async function init(){try{const c=await fetch('/api/config').then(r=>r.json());if(!c.supabaseUrl||!c.supabaseAnonKey)throw 0;supabaseClient=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);supabaseClient.auth.onAuthStateChange((e,s)=>{if(e==='PASSWORD_RECOVERY')showView('reset');else updateSession(s?.user||null)});const {data}=await supabaseClient.auth.getSession();updateSession(data.session?.user||null)}catch{msg('Configure SUPABASE_URL e SUPABASE_ANON_KEY no Vercel.')}}
function key(){return `aulafacil_profile_${currentUser?.id||'none'}`}
function updateSession(user){currentUser=user;if(!user){$('authScreen').classList.remove('hidden');$('app').classList.add('hidden');return}$('authScreen').classList.add('hidden');$('app').classList.remove('hidden');profile=JSON.parse(localStorage.getItem(key())||'{}');if(!profile.name)profile.name=user.user_metadata?.full_name||'';refreshProfile();if(!profile.school)setTimeout(()=>openProfile(),200)}
function refreshProfile(){$('welcomeName').textContent=profile.name||'Professor(a)';$('summarySchool').textContent=profile.school||'Configure seu perfil';$('profileName').value=profile.name||'';$('profileSchool').value=profile.school||'';['summaryLogo','logoPreview'].forEach(id=>{const el=$(id);if(profile.logo){el.src=profile.logo;el.style.display='block'}else el.style.display='none'})}
$('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)msg('E-mail ou senha incorretos.')};
$('registerForm').onsubmit=async e=>{e.preventDefault();if($('registerPassword').value!==$('registerConfirm').value)return msg('As senhas não são iguais.');const {data,error}=await supabaseClient.auth.signUp({email:$('registerEmail').value.trim(),password:$('registerPassword').value,options:{data:{full_name:$('registerName').value.trim()},emailRedirectTo:location.origin}});if(error)return msg(error.message);if(!data.session){showView('login');msg('Conta criada. Confirme seu e-mail para entrar.')}};
$('forgotForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.resetPasswordForEmail($('forgotEmail').value.trim(),{redirectTo:location.origin});msg(error?error.message:'Link enviado para seu e-mail.')};
$('resetForm').onsubmit=async e=>{e.preventDefault();if($('resetPassword').value!==$('resetConfirm').value)return msg('As senhas não são iguais.');const {error}=await supabaseClient.auth.updateUser({password:$('resetPassword').value});msg(error?error.message:'Senha alterada com sucesso.')};
$('logoutBtn').onclick=()=>supabaseClient.auth.signOut();
function openProfile(){$('profileModal').classList.remove('hidden');refreshProfile()} $('profileBtn').onclick=openProfile;$('closeProfile').onclick=()=>{$('profileModal').classList.add('hidden')};
$('profileLogo').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>1200000)return alert('Escolha uma imagem com até 1,2 MB.');const r=new FileReader();r.onload=()=>{profile.logo=r.result;$('logoPreview').src=r.result;$('logoPreview').style.display='block'};r.readAsDataURL(f)};
$('profileForm').onsubmit=e=>{e.preventDefault();profile.name=$('profileName').value.trim();profile.school=$('profileSchool').value.trim();localStorage.setItem(key(),JSON.stringify(profile));refreshProfile();$('profileModal').classList.add('hidden')};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));$('activityPage').classList.toggle('hidden',b.dataset.page!=='activity');$('reportPage').classList.toggle('hidden',b.dataset.page!=='report')});
function logoHtml(){return profile.logo?`<img src="${profile.logo}" alt="Logo">`:`<div style="width:72px;height:72px;border:1px dashed #aaa;display:grid;place-items:center;font-size:11px">LOGO</div>`}
function headerHtml(extra=''){return `<div class="worksheet-head">${logoHtml()}<div><h2>${esc(profile.school||'Nome da escola')}</h2><p>Professor(a): <strong>${esc(profile.name||'Professor(a)')}</strong></p>${extra}</div></div>`}
function validateClientActivity(a,p){
  if(!a||!Array.isArray(a.questions)||a.questions.length!==p.quantity)throw new Error('A atividade retornada está incompleta.');
  const requested=String(p.questionType).toLowerCase();
  a.questions.forEach((q,i)=>{
    q.number=i+1;
    if(q.type==='objective'){
      if(!Array.isArray(q.options)||q.options.length!==4)throw new Error(`A questão ${i+1} não possui quatro alternativas.`);
      if(!['A','B','C','D'].includes(q.correctOption))throw new Error(`O gabarito da questão ${i+1} está inválido.`);
      q.answer=q.answer||`${q.correctOption}) ${q.options['ABCD'.indexOf(q.correctOption)]}`;
    }else{
      q.options=null;
      q.answer=q.answer||q.expectedAnswer;
      if(!q.answer||/resposta coerente|resposta pessoal|resposta adequada|qualquer resposta|informação correta|informação verdadeira|de acordo com o tema/i.test(q.answer))throw new Error(`A resposta da questão ${i+1} está genérica.`);
    }
  });
  if(requested.includes('objet')&&a.questions.some(q=>q.type!=='objective'))throw new Error('A IA retornou questão discursiva em uma atividade objetiva.');
  if(requested.includes('disc')&&a.questions.some(q=>q.type!=='discursive'))throw new Error('A IA retornou questão objetiva em uma atividade discursiva.');
  return a;
}
$('activityForm').onsubmit=async e=>{e.preventDefault();if(!profile.name||!profile.school)return openProfile();const p={subject:$('subject').value,grade:$('grade').value,topic:$('topic').value.trim(),quantity:Number($('quantity').value),difficulty:$('difficulty').value,questionType:$('questionType').value,printStyle:$('printStyle').value,illustrations:$('illustrations').value,autism:$('autism').value,extraInstructions:$('extra').value.trim()};$('generateBtn').disabled=true;$('generateBtn').textContent='Gerando...';try{const r=await fetch('/api/generate-activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erro ao gerar atividade.');currentActivity=validateClientActivity(data,p);renderActivity()}catch(error){console.error(error);alert(error.message||'Não foi possível gerar a atividade. Tente novamente.')}finally{$('generateBtn').disabled=false;$('generateBtn').textContent='Gerar atividade'}};

function illustrationSvg(code='book'){
  const common='viewBox="0 0 180 100" role="img" aria-label="Ilustração educativa"';
  const svgs={
    book:`<svg ${common}><rect x="28" y="22" width="58" height="58" rx="7" fill="#eef2ff" stroke="#4f46e5" stroke-width="3"/><rect x="94" y="22" width="58" height="58" rx="7" fill="#eef2ff" stroke="#4f46e5" stroke-width="3"/><path d="M90 25v55" stroke="#4f46e5" stroke-width="3"/><path d="M40 38h34M40 50h28M106 38h34M106 50h28" stroke="#818cf8" stroke-width="3" stroke-linecap="round"/></svg>`,
    numbers:`<svg ${common}><circle cx="42" cy="50" r="27" fill="#ecfeff" stroke="#0891b2" stroke-width="3"/><circle cx="90" cy="50" r="27" fill="#f0fdf4" stroke="#16a34a" stroke-width="3"/><circle cx="138" cy="50" r="27" fill="#fff7ed" stroke="#ea580c" stroke-width="3"/><text x="42" y="60" text-anchor="middle" font-size="30" font-weight="700">1</text><text x="90" y="60" text-anchor="middle" font-size="30" font-weight="700">2</text><text x="138" y="60" text-anchor="middle" font-size="30" font-weight="700">3</text></svg>`,
    apple:`<svg ${common}><path d="M90 31c-24-17-49 2-42 30 8 33 31 28 42 18 11 10 34 15 42-18 7-28-18-47-42-30z" fill="#fee2e2" stroke="#dc2626" stroke-width="3"/><path d="M90 31c0-13 7-20 18-23" stroke="#166534" stroke-width="4" fill="none"/><path d="M101 14c12-7 21-2 24 5-12 5-20 2-24-5z" fill="#86efac" stroke="#166534" stroke-width="2"/></svg>`,
    globe:`<svg ${common}><circle cx="90" cy="50" r="38" fill="#e0f2fe" stroke="#0284c7" stroke-width="3"/><path d="M52 50h76M90 12c18 19 18 57 0 76M90 12c-18 19-18 57 0 76M60 29c20 8 40 8 60 0M60 71c20-8 40-8 60 0" fill="none" stroke="#0284c7" stroke-width="2"/></svg>`,
    leaf:`<svg ${common}><path d="M145 18C88 16 44 34 35 81c48 9 91-10 110-63z" fill="#dcfce7" stroke="#16a34a" stroke-width="3"/><path d="M42 76c29-21 55-34 91-47M77 53l-4-20M99 41l14 17" fill="none" stroke="#15803d" stroke-width="3" stroke-linecap="round"/></svg>`,
    animal:`<svg ${common}><circle cx="90" cy="53" r="31" fill="#fef3c7" stroke="#d97706" stroke-width="3"/><path d="M64 31 53 14l25 8M116 31l11-17-25 8" fill="#fef3c7" stroke="#d97706" stroke-width="3"/><circle cx="79" cy="49" r="3"/><circle cx="101" cy="49" r="3"/><path d="M86 61h8M90 61v7M82 70c5 5 11 5 16 0" fill="none" stroke="#92400e" stroke-width="3" stroke-linecap="round"/></svg>`,
    shapes:`<svg ${common}><circle cx="42" cy="50" r="24" fill="#dbeafe" stroke="#2563eb" stroke-width="3"/><rect x="72" y="27" width="46" height="46" rx="4" fill="#fce7f3" stroke="#db2777" stroke-width="3"/><path d="m142 23 27 52h-54z" fill="#fef3c7" stroke="#d97706" stroke-width="3"/></svg>`,
    people:`<svg ${common}><circle cx="62" cy="35" r="14" fill="#ddd6fe" stroke="#7c3aed" stroke-width="3"/><circle cx="118" cy="35" r="14" fill="#bae6fd" stroke="#0284c7" stroke-width="3"/><path d="M38 85c2-25 12-36 24-36s22 11 24 36M94 85c2-25 12-36 24-36s22 11 24 36" fill="none" stroke-width="4" stroke-linecap="round" stroke="#64748b"/></svg>`,
    speech:`<svg ${common}><path d="M30 22h120v52H88L67 91l5-17H30z" fill="#f5f3ff" stroke="#7c3aed" stroke-width="3"/><circle cx="65" cy="48" r="5" fill="#7c3aed"/><circle cx="90" cy="48" r="5" fill="#7c3aed"/><circle cx="115" cy="48" r="5" fill="#7c3aed"/></svg>`,
    science:`<svg ${common}><path d="M73 14h34M80 14v29L52 83h76l-28-40V14" fill="#ecfeff" stroke="#0891b2" stroke-width="3" stroke-linejoin="round"/><path d="M65 67h50" stroke="#06b6d4" stroke-width="12"/><circle cx="80" cy="59" r="4" fill="#fff"/><circle cx="101" cy="74" r="5" fill="#fff"/></svg>`
  };
  return `<div class="question-illustration">${svgs[String(code).trim().toLowerCase()]||svgs.book}</div>`;
}
function renderActivity(){const a=currentActivity;const q=a.questions.map(x=>`<div class="question"><strong>${x.number}. ${esc(x.prompt)}</strong>${x.visualSupport?illustrationSvg(x.visualSupport):''}${x.options?`<div class="options">${x.options.map((o,i)=>`<span>(${String.fromCharCode(65+i)}) ${esc(o)}</span>`).join('')}</div>`:'<div class="answer-lines"></div>'}</div>`).join('');$('studentPreview').innerHTML=`${headerHtml()}<div class="student-fields"><div class="line">Aluno(a):</div><div class="line">Data:</div></div><div class="paper-title"><h2>${esc(a.title)}</h2><p>${esc(a.grade)} • ${esc(a.difficulty||'')}</p></div><p><strong>Orientações:</strong> ${esc(a.instructions)}</p>${q}`;$('teacherPreview').innerHTML=`${headerHtml('<span class="exclusive">USO EXCLUSIVO DO PROFESSOR</span>')}<div class="paper-title"><h2>Gabarito — ${esc(a.title)}</h2></div>${a.questions.map(x=>`<p><strong>${x.number}.</strong> ${esc(x.answer)}</p>`).join('')}`;$('activityResult').classList.remove('hidden');$('activityResult').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('studentPreview').classList.toggle('hidden',b.dataset.tab!=='student');$('teacherPreview').classList.toggle('hidden',b.dataset.tab!=='teacher')});
function makePdf(elementId,file){const {jsPDF}=window.jspdf;const el=$(elementId);const doc=new jsPDF({unit:'pt',format:'a4'});doc.html(el,{callback:d=>d.save(file),x:25,y:25,width:545,windowWidth:794,html2canvas:{scale:.72,useCORS:true}})}
$('studentPdf').onclick=()=>makePdf('studentPreview','atividade-aluno.pdf');$('teacherPdf').onclick=()=>makePdf('teacherPreview','gabarito-professor.pdf');$('newActivity').onclick=()=>{$('activityResult').classList.add('hidden');$('activityForm').reset();scrollTo({top:0,behavior:'smooth'})};
$('reportForm').onsubmit=e=>{e.preventDefault();if(!profile.name||!profile.school)return openProfile();const d={type:$('reportType').value,clazz:$('reportClass').value,period:$('reportPeriod').value,student:$('reportStudent').value,situation:$('reportSituation').value,difficulties:$('reportDifficulties').value,actions:$('reportActions').value,results:$('reportResults').value,next:$('reportNext').value};currentReport=`Durante o período ${d.period}, na turma ${d.clazz}${d.student?`, com atenção ao(à) estudante ${d.student}`:''}, observou-se o seguinte: ${d.situation}\n\nAs principais dificuldades identificadas foram: ${d.difficulties||'não foram registradas dificuldades específicas'}.\n\nAs ações pedagógicas realizadas incluíram: ${d.actions||'acompanhamento contínuo e orientações em sala'}.\n\nQuanto aos resultados, percebeu-se: ${d.results||'a necessidade de continuidade do acompanhamento'}.\n\nComo encaminhamentos para o próximo período, recomenda-se: ${d.next||'manter o acompanhamento pedagógico e reavaliar as estratégias adotadas'}.`; $('reportPreview').innerHTML=`${headerHtml()}<div class="paper-title"><h2>${esc(d.type)}</h2><p>Turma: ${esc(d.clazz)} • Período: ${esc(d.period)}</p></div><div class="report-text">${esc(currentReport)}</div><div style="margin-top:70px;display:grid;grid-template-columns:1fr 1fr;gap:35px"><div class="line">Data:</div><div class="line">Assinatura:</div></div>`;$('reportResult').classList.remove('hidden');$('reportResult').scrollIntoView({behavior:'smooth'})};
$('reportPdf').onclick=()=>makePdf('reportPreview','relatorio-ac.pdf');$('newReport').onclick=()=>{$('reportResult').classList.add('hidden');$('reportForm').reset()};
init();
